name: CI for MISS_HIT
on: [push]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup tools
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Run test-suite
        run: |
          make test
